// Cross-stack correctness gate. This loads the JSON vector generated by the Go
// side (exec/relay/secure/vector_test.go) with the flynn/noise engine under a
// fixed random source, then drives the TypeScript mirror with the SAME keys and
// asserts byte-for-byte agreement. If Go and TS ever diverge, this fails.
//
// What it proves (all against Go-emitted bytes):
//   1. msg1 byte-identical      -> IK write path, MixKey/MixHash/EncryptAndHash
//                                  order, Noise HKDF, ChaCha nonce/AD all match.
//   2. TS opens Go's msg2       -> IK read path (DHEE/DHSE) + DecryptAndHash.
//   3. cs2 (dec) opens Go frame -> Split output order + transport nonce/AD.
//   4. cs1 (enc) seal == Go     -> same, other direction (byte-identical).
//   5. TS responder msg2 == Go  -> responder write path byte-identical.
//   6. fingerprint == Go value  -> sha256 + base32(no-pad) grouping match.
//   7. frame JSON == Go value   -> ReqPayload marshaling (tags/order) match.

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { decodeBase64, encodeBase64 } from "../src/codec";
import {
  encodeReqPayload,
  openFrame,
  sealReq,
  type ReqPayload,
} from "../src/frame";
import {
  PROTOCOL_NAME,
  fingerprint,
  generateKeypair,
  keypairFromPrivateKey,
  newInitiator,
  newResponder,
} from "../src/noise";

interface Vector {
  protocolName: string;
  initStaticPriv: string;
  initStaticPub: string;
  respStaticPriv: string;
  respStaticPub: string;
  initEphPriv: string;
  respEphPriv: string;
  prologue: string;
  payload1: string;
  payload2: string;
  msg1: string;
  msg2: string;
  respStaticFingerprint: string;
  transport: {
    plaintextI: string;
    initiatorSealed: string;
    plaintextR: string;
    responderSealed: string;
  };
  reqPayloadJSON: string;
}

const vector = JSON.parse(
  readFileSync(new URL("../testdata/ik-vector.json", import.meta.url), "utf8"),
) as Vector;

const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const b = (s: string) => decodeBase64(s);

describe("Noise IK cross-stack vector (Go flynn/noise <-> TS)", () => {
  const initStatic = keypairFromPrivateKey(b(vector.initStaticPriv));
  const respStatic = keypairFromPrivateKey(b(vector.respStaticPriv));
  const initEph = keypairFromPrivateKey(b(vector.initEphPriv));
  const respEph = keypairFromPrivateKey(b(vector.respEphPriv));

  it("suite name matches", () => {
    expect(vector.protocolName).toBe(PROTOCOL_NAME);
  });

  it("derives the same public keys as Go (X25519 clamping matches)", () => {
    expect(hex(initStatic.publicKey)).toBe(hex(b(vector.initStaticPub)));
    expect(hex(respStatic.publicKey)).toBe(hex(b(vector.respStaticPub)));
  });

  it("(1) TS initiator produces msg1 byte-identical to Go", () => {
    const init = newInitiator(initStatic, respStatic.publicKey, { ephemeral: initEph });
    const msg1 = init.writeMessage(b(vector.payload1));
    expect(hex(msg1)).toBe(hex(b(vector.msg1)));
  });

  it("(2-4) TS initiator opens Go msg2, then transport keys match both ways", () => {
    const init = newInitiator(initStatic, respStatic.publicKey, { ephemeral: initEph });
    // must write msg1 first (advances the state machine) before reading msg2
    init.writeMessage(b(vector.payload1));

    const payload2 = init.readMessage(b(vector.msg2));
    expect(hex(payload2)).toBe(hex(b(vector.payload2)));

    const sess = init.session();
    expect(sess).not.toBeNull();

    // (3) cs2/dec: TS opens the frame Go's responder sealed.
    const openedR = sess!.open(b(vector.transport.responderSealed));
    expect(hex(openedR)).toBe(hex(b(vector.transport.plaintextR)));

    // (4) cs1/enc: TS seals the same plaintext Go's initiator sealed -> identical bytes.
    const sealedI = sess!.seal(b(vector.transport.plaintextI));
    expect(hex(sealedI)).toBe(hex(b(vector.transport.initiatorSealed)));
  });

  it("(5) TS responder reproduces Go msg2 byte-identical and interops on transport", () => {
    const resp = newResponder(respStatic, { ephemeral: respEph });
    const payload1 = resp.readMessage(b(vector.msg1));
    expect(hex(payload1)).toBe(hex(b(vector.payload1)));

    const msg2 = resp.writeMessage(b(vector.payload2));
    expect(hex(msg2)).toBe(hex(b(vector.msg2)));

    const sess = resp.session();
    expect(sess).not.toBeNull();
    // responder dec=cs1 opens Go's initiator-sealed frame.
    const openedI = sess!.open(b(vector.transport.initiatorSealed));
    expect(hex(openedI)).toBe(hex(b(vector.transport.plaintextI)));
    // responder enc=cs2 seal matches Go's responder-sealed frame.
    const sealedR = sess!.seal(b(vector.transport.plaintextR));
    expect(hex(sealedR)).toBe(hex(b(vector.transport.responderSealed)));
  });

  it("(6) fingerprint(respStaticPub) matches the Go value", () => {
    expect(fingerprint(respStatic.publicKey)).toBe(vector.respStaticFingerprint);
  });

  it("(7) frame ReqPayload marshals byte-identical to Go's encoding/json", () => {
    const rp: ReqPayload = { id: "r1", method: "GET", path: "/api/summary" };
    expect(encodeBase64(encodeReqPayload(rp))).toBe(vector.reqPayloadJSON);
  });
});

describe("TS-only round trips (self-consistency)", () => {
  it("initiator <-> responder complete a full handshake and exchange frames", () => {
    const daemon = generateKeypair();
    const client = generateKeypair();

    const init = newInitiator(client, daemon.publicKey);
    const resp = newResponder(daemon);

    const msg1 = init.writeMessage();
    const p1 = resp.readMessage(msg1);
    expect(p1.length).toBe(0);

    const msg2 = resp.writeMessage();
    const p2 = init.readMessage(msg2);
    expect(p2.length).toBe(0);

    const cli = init.session()!;
    const srv = resp.session()!;
    expect(cli).not.toBeNull();
    expect(srv).not.toBeNull();

    // client -> daemon
    const ct = cli.seal(new TextEncoder().encode("GET /api/board"));
    expect(new TextDecoder().decode(srv.open(ct))).toBe("GET /api/board");
    // daemon -> client
    const ct2 = srv.seal(new TextEncoder().encode("200 ok"));
    expect(new TextDecoder().decode(cli.open(ct2))).toBe("200 ok");
  });

  it("a wrong pinned key fails the handshake (IK authentication)", () => {
    const daemon = generateKeypair();
    const evil = generateKeypair();
    const client = generateKeypair();

    const init = newInitiator(client, evil.publicKey); // pins the wrong key
    const resp = newResponder(daemon);

    const msg1 = init.writeMessage();
    expect(() => resp.readMessage(msg1)).toThrow();
  });

  it("frame layer: sealed req round-trips through a real handshake", () => {
    const daemon = generateKeypair();
    const client = generateKeypair();
    const init = newInitiator(client, daemon.publicKey);
    const resp = newResponder(daemon);
    resp.readMessage(init.writeMessage());
    init.readMessage(resp.writeMessage());
    const cli = init.session()!;
    const srv = resp.session()!;

    const rp: ReqPayload = {
      id: "r7",
      method: "POST",
      path: "/api/task",
      headers: { accept: "application/json" },
      body: new TextEncoder().encode('{"goal":"ship"}'),
    };
    const frame = sealReq(cli, "s1", rp);
    expect(frame.kind).toBe("req");
    const pt = openFrame(srv, frame, "req");
    const parsed = JSON.parse(new TextDecoder().decode(pt));
    expect(parsed.id).toBe("r7");
    expect(parsed.method).toBe("POST");
    expect(parsed.path).toBe("/api/task");
    expect(parsed.headers.accept).toBe("application/json");
    // body is base64 of the raw bytes, matching Go's []byte JSON convention.
    expect(new TextDecoder().decode(decodeBase64(parsed.body))).toBe('{"goal":"ship"}');
  });

  it("tampered transport frame is rejected", () => {
    const daemon = generateKeypair();
    const client = generateKeypair();
    const init = newInitiator(client, daemon.publicKey);
    const resp = newResponder(daemon);
    resp.readMessage(init.writeMessage());
    init.readMessage(resp.writeMessage());
    const cli = init.session()!;
    const srv = resp.session()!;

    const ct = cli.seal(new TextEncoder().encode("secret"));
    ct[ct.length - 1] = (ct[ct.length - 1] ?? 0) ^ 0x01;
    expect(() => srv.open(ct)).toThrow();
  });
});
