package ui

import "net/http"

// handleAgentChannelPage serves the agent-first chat shell. It consumes only
// the parent-qualified Agent Channel API; the legacy Primary Channels page and
// /api/channels contract remain separate rollback surfaces.
func (s *Server) handleAgentChannelPage(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Security-Policy", "default-src 'self'; img-src 'self' data:; connect-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(agentChannelPageHTML))
}

const agentChannelPageHTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="dark light">
<title>Fort · Agent Channels</title>
<link rel="icon" href="/fort-icon.png">
<style>
:root{
  color-scheme:dark;--bg:#101512;--rail:#141a16;--panel:#181f1b;--raised:#202921;
  --line:#303a31;--line-strong:#596845;--text:#f1f4ec;--body:#d7ddd2;
  --muted:#9ca69a;--faint:#737e71;--accent:#c5e75d;--accent-soft:#303a23;
  --accent-ink:#152006;--good:#a8cd65;--warn:#f2b54a;--bad:#e78568;
  --shadow:0 20px 58px rgba(0,0,0,.3);--font:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  --mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace
}
*{box-sizing:border-box}
html,body{height:100%;margin:0;overflow:hidden}
body{background:var(--bg);color:var(--text);font:14px/1.45 var(--font);text-rendering:optimizeLegibility}
button,input,textarea{font:inherit}button{min-height:44px;color:inherit;cursor:pointer}button:disabled{cursor:not-allowed;opacity:.5}
button:focus-visible,input:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid var(--accent);outline-offset:2px}
.skip-link{position:fixed;left:12px;top:8px;z-index:100;background:var(--accent);color:var(--accent-ink);padding:9px 12px;border-radius:8px;transform:translateY(-160%)}
.skip-link:focus{transform:none}
.shell{height:100dvh;display:grid;grid-template-columns:310px minmax(0,1fr)}
.rail{min-width:0;display:flex;flex-direction:column;background:var(--rail);border-right:1px solid var(--line);z-index:30}
.brand{height:68px;display:flex;align-items:center;gap:11px;padding:11px 16px;border-bottom:1px solid var(--line)}
.brand-copy{min-width:0}.brand-copy strong{display:block;letter-spacing:.22em;font-size:13px}.brand-copy span{display:block;margin-top:2px;color:var(--muted);font-size:10px}
.fort-mark{position:relative;display:grid;place-items:center;width:38px;height:38px;flex:none;isolation:isolate;contain:paint}
.fort-mark::before,.fort-mark::after{content:"";position:absolute;inset:4px;border:1px solid color-mix(in srgb,var(--accent) 68%,transparent);border-radius:50%;opacity:.82}
.fort-mark::before{animation:fort-ambient 7.2s linear infinite;box-shadow:0 0 12px color-mix(in srgb,var(--accent) 24%,transparent)}
.fort-mark::after{inset:9px;border-style:dashed;animation:fort-ambient 10.8s linear infinite reverse;opacity:.55}
.fort-mark-core{width:17px;height:17px;border-radius:50%;background:radial-gradient(circle at 34% 28%,#fff 0 8%,var(--accent) 22%,#4f7f2f 62%,#182216 100%);box-shadow:0 0 10px color-mix(in srgb,var(--accent) 48%,transparent);animation:fort-glow 5.4s ease-in-out infinite}
.fort-mark[data-energy="working"]::before{animation-duration:2.8s;inset:1px;border-width:2px}.fort-mark[data-energy="working"]::after{animation-duration:4.2s;inset:7px;opacity:.8}
.fort-mark[data-energy="working"] .fort-mark-core{animation-duration:2.3s}
.fort-mark[data-motion="paused"]::before,.fort-mark[data-motion="paused"]::after,.fort-mark[data-motion="paused"] .fort-mark-core{animation-play-state:paused}
@keyframes fort-ambient{0%{transform:rotate(0deg) translateX(.55px)}50%{transform:rotate(180deg) translateX(-.55px)}100%{transform:rotate(360deg) translateX(.55px)}}
@keyframes fort-glow{0%,100%{opacity:.83;filter:brightness(.88);box-shadow:0 0 7px color-mix(in srgb,var(--accent) 30%,transparent)}50%{opacity:1;filter:brightness(1.12);box-shadow:0 0 15px color-mix(in srgb,var(--accent) 54%,transparent)}}
.rail-actions{padding:12px 13px 7px;display:grid;grid-template-columns:1fr auto;gap:7px}
.primary,.secondary,.quiet,.icon-button{border-radius:9px}.primary{border:1px solid var(--accent);background:var(--accent);color:var(--accent-ink);font-weight:750;padding:8px 12px}.secondary{border:1px solid var(--line-strong);background:var(--accent-soft);padding:8px 12px}.quiet,.icon-button{border:1px solid transparent;background:transparent;color:var(--muted);padding:8px 10px}.quiet:hover,.icon-button:hover{background:var(--raised);color:var(--text)}
.agent-scroll{min-height:0;flex:1;overflow:auto;padding:4px 9px 16px;scrollbar-gutter:stable}
.rail-heading{display:flex;align-items:center;justify-content:space-between;min-height:31px;padding:0 8px;color:var(--faint);font-size:10px;font-weight:750;letter-spacing:.1em;text-transform:uppercase}
.agent-channel-row{margin:4px 0 9px;border:1px solid transparent;border-radius:10px}.agent-channel-row[data-selected="true"]{border-color:var(--line);background:color-mix(in srgb,var(--raised) 62%,transparent)}
.agent-button{width:100%;min-height:52px;display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:9px;border:0;border-radius:9px;background:transparent;padding:7px;text-align:left}
.agent-button:hover{background:var(--raised)}
.agent-avatar{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(145deg,#31462b,#25352c);border:1px solid var(--line-strong);color:var(--accent);font-size:12px;font-weight:800;letter-spacing:.05em;text-transform:uppercase;overflow:hidden}
.agent-button-copy{min-width:0}.agent-button-copy strong,.agent-button-copy span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.agent-button-copy strong{font-size:12.5px}.agent-button-copy span{margin-top:2px;color:var(--muted);font-size:10px}.readiness-dot{width:8px;height:8px;border-radius:50%;background:var(--faint)}.readiness-dot.ready{background:var(--good)}.readiness-dot.unavailable,.readiness-dot.drifted{background:var(--bad)}
.conversation-groups{display:grid;gap:8px;padding:2px 6px 7px 49px}.conversation-group[hidden]{display:none}.conversation-group-label{display:block;margin:2px 0 3px;color:var(--faint);font-size:9px;font-weight:750;letter-spacing:.06em;text-transform:uppercase}
.conversation-list{display:grid;gap:2px}.conversation-button{width:100%;min-height:34px;border:0;border-radius:7px;background:transparent;color:var(--muted);padding:6px 8px;text-align:left;font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.conversation-button:hover,.conversation-button[aria-current="page"]{background:var(--raised);color:var(--text)}.conversation-button .pin{color:var(--accent);margin-right:4px}
.rail-empty,.rail-error{padding:13px 10px;color:var(--muted);font-size:11.5px}.rail-error{color:var(--bad)}
.rail-footer{border-top:1px solid var(--line);padding:8px 10px 13px;display:grid;grid-template-columns:1fr 1fr;gap:4px}.rail-footer button{font-size:11px}
.surface{min-width:0;display:grid;grid-template-rows:58px minmax(0,1fr);background:var(--bg)}
.topbar{display:flex;align-items:center;gap:8px;border-bottom:1px solid var(--line);background:var(--panel);padding:0 17px}.menu-button{display:none}.topbar-title{min-width:0}.topbar-title strong,.topbar-title span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.topbar-title strong{font-size:12px}.topbar-title span{color:var(--muted);font-size:10px}.topbar-spacer{flex:1}.needs-button{position:relative}.needs-count{display:inline-grid;place-items:center;min-width:19px;height:19px;margin-left:4px;border-radius:10px;background:var(--bad);color:#fff;font:10px var(--mono)}
.conversation-surface{min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr) auto}.conversation-header{min-height:78px;display:flex;align-items:center;gap:11px;padding:11px 21px;border-bottom:1px solid var(--line)}.conversation-header-copy{min-width:0}.conversation-header h1{margin:0;font-size:18px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.conversation-header p{margin:4px 0 0;color:var(--muted);font-size:10.5px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.conversation-working{margin-left:auto;display:flex;align-items:center;gap:7px;color:var(--muted);font-size:10px;white-space:nowrap}.conversation-working[hidden]{display:none}.conversation-working .fort-mark{width:28px;height:28px}.conversation-working .fort-mark::before{inset:3px}.conversation-working .fort-mark::after{inset:7px}.conversation-working .fort-mark-core{width:11px;height:11px}.conversation-header-actions{display:flex;gap:2px}
.transcript{min-height:0;overflow:auto;padding:23px max(20px,calc((100% - 790px)/2)) 18px;scrollbar-gutter:stable}.empty-state,.loading-state,.error-state{min-height:100%;display:grid;place-items:center;text-align:center;padding:32px}.empty-inner{max-width:480px}.empty-inner .fort-mark{margin:0 auto 17px;width:58px;height:58px}.empty-inner .fort-mark::before{inset:5px}.empty-inner .fort-mark::after{inset:14px}.empty-inner .fort-mark-core{width:23px;height:23px}.empty-inner h2{margin:0 0 7px;font-size:22px}.empty-inner p{margin:0;color:var(--muted)}
.message{max-width:760px;margin:0 0 22px;display:grid;grid-template-columns:38px minmax(0,1fr);gap:11px}.message.human{display:block;padding-left:49px}.message-avatar{width:38px;height:38px}.message-copy{min-width:0}.message-byline{display:flex;align-items:baseline;gap:8px;margin-bottom:4px}.message-byline strong{font-size:12px}.message-byline time{color:var(--faint);font:10px var(--mono)}.message-body{margin:0;color:var(--body);white-space:pre-wrap;overflow-wrap:anywhere}.message-attribution{margin:6px 0 0;color:var(--faint);font:9.5px/1.4 var(--mono);overflow-wrap:anywhere}
.target{max-width:711px;margin:-13px 0 20px 49px;border:1px solid var(--line);border-radius:9px;background:var(--panel);padding:9px 11px}.target-head{display:flex;align-items:center;gap:9px}.target-copy{min-width:0;flex:1}.target-copy strong,.target-copy span{display:block}.target-copy strong{font-size:11px;text-transform:capitalize}.target-copy span{margin-top:2px;color:var(--muted);font-size:10px;overflow-wrap:anywhere}.target-actions{display:flex;gap:5px}.target.failed{border-color:color-mix(in srgb,var(--bad) 62%,var(--line))}.target.working,.target.queued{border-color:color-mix(in srgb,var(--warn) 52%,var(--line))}
.composer-shell{border-top:1px solid var(--line);background:var(--panel);padding:10px max(18px,calc((100% - 810px)/2)) 14px}.composer-context{display:flex;justify-content:space-between;gap:12px;margin:0 3px 7px;color:var(--muted);font-size:10px}.composer{display:flex;align-items:flex-end;gap:8px;border:1px solid var(--line-strong);border-radius:11px;background:var(--bg);padding:7px}.composer textarea{min-width:0;min-height:44px;max-height:155px;flex:1;resize:vertical;border:0;background:transparent;color:var(--text);padding:11px}.composer textarea::placeholder{color:var(--faint)}.composer-status{min-height:17px;margin:4px 3px 0;color:var(--muted);font-size:10px}.composer-status.error{color:var(--bad)}
.notice{position:fixed;top:68px;left:50%;z-index:80;max-width:min(570px,calc(100vw - 28px));transform:translateX(-50%);border:1px solid var(--line-strong);border-radius:9px;background:var(--panel);box-shadow:var(--shadow);padding:9px 12px;color:var(--body);font-size:11px}.notice[hidden]{display:none}
.backdrop{display:none}.visually-hidden{position:absolute!important;width:1px!important;height:1px!important;margin:-1px!important;padding:0!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
dialog{width:min(640px,calc(100vw - 28px));max-height:min(82dvh,740px);padding:0;border:1px solid var(--line-strong);border-radius:12px;background:var(--panel);color:var(--text);box-shadow:var(--shadow)}dialog::backdrop{background:rgba(0,7,4,.7)}.dialog-head{display:flex;align-items:flex-start;gap:10px;padding:15px 17px;border-bottom:1px solid var(--line)}.dialog-head-copy{min-width:0;flex:1}.dialog-head h2{margin:0;font-size:17px}.dialog-head p{margin:3px 0 0;color:var(--muted);font-size:11px}.dialog-body{padding:16px 17px 20px;overflow:auto}.field{display:grid;gap:5px;margin:0 0 13px}.field label{font-size:11px;font-weight:700}.field input{min-height:44px;border:1px solid var(--line-strong);border-radius:8px;background:var(--bg);color:var(--text);padding:9px 10px}.dialog-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:13px}.option-list,.needs-list,.archived-list{display:grid;gap:7px}.option-card,.needs-card,.identity-card,.archived-card{border:1px solid var(--line);border-radius:9px;background:var(--bg);padding:10px}.option-card-head,.archived-card-head{display:flex;align-items:center;gap:10px}.option-card-head strong,.archived-card-head strong{min-width:0;flex:1}.option-card p,.needs-card p,.archived-card p{margin:5px 0 0;color:var(--muted);font-size:10.5px}.facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px 13px;margin:10px 0 0}.facts dt{color:var(--faint);font-size:9px;text-transform:uppercase}.facts dd{margin:2px 0 0;color:var(--body);font:10px/1.35 var(--mono);overflow-wrap:anywhere}
template{display:none}
@media (prefers-reduced-motion:reduce){
  .fort-mark::before,.fort-mark::after{transform:none!important;animation:fort-glow 5.2s ease-in-out infinite!important}
  .fort-mark-core{transform:none!important;animation:fort-glow 5.2s ease-in-out infinite!important}
  *{scroll-behavior:auto!important;transition-duration:0s!important}
}
@media (max-width:850px){
  .shell{display:block}.rail{position:fixed;inset:0 auto 0 0;width:min(320px,89vw);box-shadow:var(--shadow);transform:translateX(-105%);transition:transform .18s ease}.rail[data-open="true"]{transform:none}.surface{height:100dvh}.menu-button{display:inline-flex}.backdrop[data-open="true"]{display:block;position:fixed;inset:0;z-index:25;border:0;background:rgba(0,7,4,.68);width:100%;height:100%}.conversation-header{padding:10px 12px;align-items:flex-start}.conversation-header-actions .quiet{min-width:44px;font-size:0}.conversation-header-actions .quiet::first-letter{font-size:14px}.transcript{padding:17px 12px 10px}.message{grid-template-columns:32px minmax(0,1fr);gap:8px}.message-avatar{width:32px;height:32px}.message.human{padding-left:40px}.target{margin-left:0}.composer-shell{padding:9px 9px 10px}.topbar{padding:0 10px}.facts{grid-template-columns:1fr}
}
</style>
</head>
<body>
<a class="skip-link" href="#transcript">Skip to conversation</a>
<div class="shell">
  <aside class="rail" id="agent-rail" aria-label="Agent Channels" data-open="false">
    <header class="brand">
      <span class="fort-mark" id="fort-product-mark" aria-hidden="true" data-energy="ambient" data-motion="running"><span class="fort-mark-core"></span></span>
      <div class="brand-copy"><strong>FORT</strong><span>Chat with your agents</span></div>
      <button class="icon-button menu-button" id="rail-close" type="button" aria-label="Close Channels">×</button>
    </header>
    <div class="rail-actions">
      <button class="primary" id="new-conversation" type="button">New conversation</button>
      <button class="secondary" id="add-agent" type="button" aria-label="Add Agent Channel">＋</button>
    </div>
    <div class="agent-scroll">
      <div class="rail-heading"><span>Channels</span><span id="agent-count"></span></div>
      <div id="agent-channel-list" aria-live="polite"><p class="rail-empty">Loading enrolled agents…</p></div>
      <template id="agent-channel-template">
        <article class="agent-channel-row">
          <button class="agent-button" type="button"><span class="agent-avatar"></span><span class="agent-button-copy"></span><span class="readiness-dot"></span></button>
          <div class="conversation-groups">
            <section class="conversation-group" data-kind="pinned"><span class="conversation-group-label">Pinned conversations</span><div class="conversation-list"></div></section>
            <section class="conversation-group" data-kind="recent"><span class="conversation-group-label">Recent conversations</span><div class="conversation-list"></div></section>
          </div>
        </article>
      </template>
    </div>
    <footer class="rail-footer"><button class="quiet" id="archived-conversations" type="button">Archived conversations</button><button class="quiet" id="needs-you" type="button">Needs you <span class="needs-count" id="needs-count" hidden></span></button><button class="quiet" id="settings" type="button">Settings</button></footer>
  </aside>
  <button class="backdrop" id="rail-backdrop" type="button" aria-label="Close Channels" data-open="false"></button>
  <main class="surface">
    <header class="topbar">
      <button class="icon-button menu-button" id="rail-open" type="button" aria-label="Open Agent Channels">☰</button>
      <div class="topbar-title"><strong id="topbar-agent">Agent Channels</strong><span id="topbar-readiness">Choose an enrolled agent</span></div>
      <div class="topbar-spacer"></div><button class="quiet" id="inspect-agent" type="button" hidden>Agent identity</button>
    </header>
    <section class="conversation-surface" aria-labelledby="conversation-title">
      <header class="conversation-header">
        <span class="agent-avatar" id="header-avatar" aria-hidden="true">—</span>
        <div class="conversation-header-copy"><h1 id="conversation-title">Choose an agent</h1><p id="conversation-subtitle">Channels are agents. Conversations live beneath each agent.</p></div>
        <div class="conversation-working" id="conversation-working" hidden><span class="fort-mark" id="conversation-product-mark" role="img" aria-label="Fort" data-energy="ambient" data-motion="running"><span class="fort-mark-core"></span></span><span>Selected conversation is Working</span></div>
        <div class="conversation-header-actions"><button class="quiet" id="pin-conversation" type="button" hidden>Pin</button><button class="quiet" id="rename-conversation" type="button" hidden>Rename</button><button class="quiet" id="archive-conversation" type="button" hidden>Archive</button></div>
      </header>
      <div class="transcript" id="transcript" tabindex="-1">
        <div class="empty-state"><div class="empty-inner"><span class="fort-mark" role="img" aria-label="Fort" data-energy="ambient" data-motion="running"><span class="fort-mark-core"></span></span><h2>Your agents, one place</h2><p>Choose an Agent Channel to continue a conversation or start a separate context.</p></div></div>
      </div>
      <div class="composer-shell">
        <div class="composer-context"><span id="composer-context">Choose an agent before sending.</span><span>Exact agent · no substitution</span></div>
        <form class="composer" id="conversation-composer"><label class="visually-hidden" for="message-text">Message</label><textarea id="message-text" name="text" placeholder="Message your selected agent" required disabled></textarea><button class="primary" id="send-message" type="submit" disabled>Send</button></form>
        <div class="composer-status" id="composer-status" role="status" aria-live="polite"></div>
      </div>
    </section>
  </main>
</div>
<div class="notice" id="notice" role="status" aria-live="polite" hidden></div>

<dialog id="agent-dialog"><div class="dialog-head"><div class="dialog-head-copy"><h2>Add Agent Channel</h2><p>Choose one eligible, server-resolved agent option. Identity and authority cannot be mixed.</p></div><button class="icon-button" type="button" data-close-dialog aria-label="Close">×</button></div><div class="dialog-body"><div class="option-list" id="agent-options"><p>Loading eligible agents…</p></div><div class="dialog-actions"><button class="quiet" id="archived-agents" type="button">Archived Agent Channels</button><button class="quiet" id="recheck-options" type="button">Recheck readiness</button></div></div></dialog>
<dialog id="identity-dialog"><div class="dialog-head"><div class="dialog-head-copy"><h2 id="identity-title">Agent identity</h2><p>Immutable dispatch identity and current observational readiness.</p></div><button class="icon-button" type="button" data-close-dialog aria-label="Close">×</button></div><div class="dialog-body" id="identity-content"></div></dialog>
<dialog id="name-dialog"><form id="name-form"><div class="dialog-head"><div class="dialog-head-copy"><h2 id="name-title">Name</h2><p id="name-copy">Presentation only. Agent identity does not change.</p></div><button class="icon-button" type="button" data-close-dialog aria-label="Close">×</button></div><div class="dialog-body"><div class="field"><label for="name-input">Name</label><input id="name-input" name="name" maxlength="120" required></div><div class="dialog-actions"><button class="quiet" type="button" data-close-dialog>Cancel</button><button class="primary" type="submit">Save</button></div></div></form></dialog>
<dialog id="needs-dialog"><div class="dialog-head"><div class="dialog-head-copy"><h2>Needs you</h2><p>Current durable chat failures and approvals only.</p></div><button class="icon-button" type="button" data-close-dialog aria-label="Close">×</button></div><div class="dialog-body"><div class="needs-list" id="needs-list"></div></div></dialog>
<dialog id="archived-dialog"><div class="dialog-head"><div class="dialog-head-copy"><h2>Archived conversations</h2><p>Reopen a durable conversation beneath the same Agent Channel.</p></div><button class="icon-button" type="button" data-close-dialog aria-label="Close">×</button></div><div class="dialog-body"><div class="archived-list" id="archived-list"></div></div></dialog>
<dialog id="archived-agents-dialog"><div class="dialog-head"><div class="dialog-head-copy"><h2>Archived Agent Channels</h2><p>Reopen the same immutable agent identity and its durable conversations.</p></div><button class="icon-button" type="button" data-close-dialog aria-label="Close">×</button></div><div class="dialog-body"><div class="archived-list" id="archived-agents-list"></div></div></dialog>

<script>
'use strict';
const API={agents:'/api/agent-channels',options:'/api/agent-options',needs:'/api/agent-needs-you'};
const state={agents:[],selectedAgentID:'',selectedConversationID:'',detail:null,creatingConversation:false,needs:[],eventSource:null,pendingTurnID:''};
const byID=id=>document.getElementById(id);
const list=value=>Array.isArray(value)?value:[];
const first=(...values)=>values.find(value=>value!==undefined&&value!==null&&value!=='');
const channelOf=item=>first(item&&item.channel,item&&item.agent_channel,item,{});
const conversationOf=item=>first(item&&item.conversation,item,{});
const channelID=item=>String(first(channelOf(item).id,''));
const conversationID=item=>String(first(conversationOf(item).id,''));
const selectedAgent=()=>state.agents.find(item=>channelID(item)===state.selectedAgentID)||null;
const selectedConversationSummary=()=>{const agent=selectedAgent();return list(agent&&agent.conversations).find(item=>conversationID(item)===state.selectedConversationID)||null};
const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(part=>part[0]||'').join('').toUpperCase()||'?';
const encode=value=>encodeURIComponent(String(value));
const agentURL=id=>API.agents+'/'+encode(id);
const conversationURL=(agentID,conversationID)=>agentURL(agentID)+'/conversations/'+encode(conversationID);
const firstTurnURL=agentID=>agentURL(agentID)+'/turns';
const newUUID=()=>globalThis.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
function pendingTurnKey(){return 'fort.agent-channel.pending.'+state.selectedAgentID+'.'+(state.selectedConversationID||'new')}
function pendingTurnIDFor(text){const key=pendingTurnKey();try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&saved.id&&saved.text===text){state.pendingTurnID=saved.id;return saved.id}}catch(_){}const id=newUUID();state.pendingTurnID=id;localStorage.setItem(pendingTurnKey(),JSON.stringify({id,text}));return id}
function clearPendingTurn(id){const key=pendingTurnKey();try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&saved.id===id)localStorage.removeItem(key)}catch(_){localStorage.removeItem(key)}if(state.pendingTurnID===id)state.pendingTurnID=''}
function errorText(error){return first(error&&error.message,'Fort could not complete that request.')}
async function request(url,options={}){const response=await fetch(url,{...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});let body=null;const text=await response.text();if(text){try{body=JSON.parse(text)}catch(_){body=null}}if(!response.ok){throw new Error(first(body&&body.error,body&&body.message,text,'Request failed ('+response.status+')'))}return body}
function clear(element){while(element.firstChild)element.removeChild(element.firstChild)}
function node(tag,className,text){const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)element.textContent=String(text);return element}
function announce(message,kind=''){const region=byID('notice');region.textContent=message;region.hidden=false;byID('composer-status').textContent=message;byID('composer-status').className='composer-status'+(kind?' '+kind:'');clearTimeout(announce.timer);announce.timer=setTimeout(()=>{region.hidden=true},5000)}
function setRail(open){byID('agent-rail').dataset.open=String(open);byID('rail-backdrop').dataset.open=String(open)}
function openDialog(id){const dialog=byID(id);if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}
function closeDialog(dialog){if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open')}
function readiness(item){return first(item&&item.readiness,{state:'unknown'}).state||'unknown'}
function readinessReason(item){const current=first(item&&item.readiness,{state:'unknown'});const status=String(first(current.state,'unknown'));return String(first(current.reason,status))}
function agentCanSend(){const current=first(state.detail&&state.detail.readiness,selectedAgent()&&selectedAgent().readiness,{state:'unknown'});return Boolean(state.selectedAgentID)&&String(first(current.state,'unknown'))==='ready'}
function renderAgents(){
  const container=byID('agent-channel-list');clear(container);byID('agent-count').textContent=state.agents.length?String(state.agents.length):'';
  if(!state.agents.length){container.append(node('p','rail-empty','No enrolled Agent Channels. Add an eligible agent to begin.'));return}
  state.agents.forEach(item=>{
    const channel=channelOf(item);const row=node('article','agent-channel-row');row.dataset.selected=String(channel.id===state.selectedAgentID);
    const button=node('button','agent-button');button.type='button';button.setAttribute('aria-label','Open '+first(channel.name,'Agent Channel'));const avatar=node('span','agent-avatar',initials(channel.name));avatar.setAttribute('aria-hidden','true');button.append(avatar);
    const copy=node('span','agent-button-copy');copy.append(node('strong','',first(channel.name,'Unnamed agent')));copy.append(node('span','',String(first(channel.binding&&channel.binding.seat&&channel.binding.seat.agent,'Agent'))+' · '+String(readiness(item))));button.append(copy);button.append(node('span','readiness-dot '+readiness(item)));button.addEventListener('click',()=>selectAgent(channel.id));row.append(button);
    const groups=node('div','conversation-groups');const conversations=list(item.conversations);const pinned=conversations.filter(conversation=>conversation.pinned);const recent=conversations.filter(conversation=>!conversation.pinned);
    groups.append(renderConversationGroup('Pinned conversations',pinned,'pinned',channel.id));groups.append(renderConversationGroup('Recent conversations',recent,'recent',channel.id));row.append(groups);container.append(row);
  });
}
function renderConversationGroup(label,items,kind,agentID){const section=node('section','conversation-group');section.dataset.kind=kind;section.hidden=!items.length;section.append(node('span','conversation-group-label',label));const container=node('div','conversation-list');items.forEach(item=>{const conversation=conversationOf(item);const button=node('button','conversation-button');button.type='button';button.setAttribute('aria-current',conversation.id===state.selectedConversationID?'page':'false');if(item.pinned)button.append(node('span','pin','◆'));button.append(document.createTextNode(first(conversation.title,conversation.name,'Untitled conversation')));button.addEventListener('click',event=>{event.stopPropagation();openConversation(agentID,conversation.id)});container.append(button)});section.append(container);return section}
async function loadAgents(preferredAgentID='',preferredConversationID=''){
  const payload=await request(API.agents+'?state=open');state.agents=Array.isArray(payload)?payload:list(payload&&payload.items);
  const storedAgent=localStorage.getItem('fort.agent-channel.last')||'';const nextAgent=first(preferredAgentID,storedAgent,'');state.selectedAgentID=state.agents.some(item=>channelID(item)===nextAgent)?nextAgent:'';renderAgents();
  if(!state.selectedAgentID){renderWelcome();return}
  const agent=selectedAgent();const conversationKey='fort.agent-channel.'+state.selectedAgentID+'.conversation';const storedConversation=localStorage.getItem(conversationKey)||'';const conversations=list(agent&&agent.conversations);const nextConversation=first(preferredConversationID,storedConversation,'');
  if(conversations.some(item=>conversationID(item)===nextConversation))await openConversation(state.selectedAgentID,nextConversation);else await selectAgent(state.selectedAgentID);
}
async function selectAgent(id){stopConversationEvents();state.selectedAgentID=id;state.selectedConversationID='';state.detail=null;state.creatingConversation=true;localStorage.setItem('fort.agent-channel.last',id);renderAgents();renderNewConversation();setRail(false)}
function agentHeader(item,observedReadiness=null){const channel=channelOf(item);const current=first(observedReadiness,item&&item.readiness,{state:'unknown'});const status=String(first(current.state,'unknown'));const canSend=status==='ready';byID('topbar-agent').textContent=first(channel.name,'Agent Channel');byID('topbar-readiness').textContent=status+' · '+first(current.reason,status);byID('header-avatar').textContent=initials(channel.name);byID('inspect-agent').hidden=false;byID('composer-context').textContent=canSend?'New conversation with '+first(channel.name,'selected agent'):'Send blocked: '+first(current.reason,status);byID('message-text').disabled=!canSend;byID('send-message').disabled=!canSend}
function renderWelcome(){stopConversationEvents();state.selectedAgentID='';state.selectedConversationID='';byID('topbar-agent').textContent='Agent Channels';byID('topbar-readiness').textContent='Choose an enrolled agent';byID('conversation-title').textContent='Choose an agent';byID('conversation-subtitle').textContent='Channels are agents. Conversations live beneath each agent.';byID('header-avatar').textContent='—';byID('inspect-agent').hidden=true;byID('pin-conversation').hidden=true;byID('rename-conversation').hidden=true;byID('archive-conversation').hidden=true;byID('message-text').disabled=true;byID('send-message').disabled=true;byID('composer-context').textContent='Choose an agent before sending.';const transcript=byID('transcript');transcript.innerHTML='<div class="empty-state"><div class="empty-inner"><span class="fort-mark" role="img" aria-label="Fort" data-energy="ambient" data-motion="running"><span class="fort-mark-core"></span></span><h2>Your agents, one place</h2><p>Choose an Agent Channel to continue a conversation or start a separate context.</p></div></div>';renderWorkingEnergy(null);syncMarkLifecycle()}
function renderNewConversation(){const agent=selectedAgent();if(!agent){renderWelcome();return}agentHeader(agent);state.creatingConversation=true;byID('conversation-title').textContent='New conversation';byID('conversation-subtitle').textContent='A separate durable context beneath '+first(channelOf(agent).name,'this agent')+'. The first Send creates both the conversation and its first turn.';byID('pin-conversation').hidden=true;byID('rename-conversation').hidden=true;byID('archive-conversation').hidden=true;const transcript=byID('transcript');clear(transcript);const empty=node('div','empty-state');const inner=node('div','empty-inner');inner.append(node('h2','', 'Start a new conversation'));inner.append(node('p','', 'Your first message is committed atomically with this new transcript. No other conversation context is included.'));empty.append(inner);transcript.append(empty);renderWorkingEnergy(null);byID('message-text').focus()}
function stopConversationEvents(){if(state.eventSource){state.eventSource.close();state.eventSource=null}}
function startConversationEvents(agentID,id){stopConversationEvents();if(typeof EventSource!=='function')return;const source=new EventSource(conversationURL(agentID,id)+'/events');state.eventSource=source;source.onmessage=event=>{if(state.selectedAgentID!==agentID||state.selectedConversationID!==id)return;try{state.detail=JSON.parse(event.data);renderConversation()}catch(_){}}}
async function openConversation(agentID,id){stopConversationEvents();state.selectedAgentID=agentID;state.selectedConversationID=id;state.creatingConversation=false;localStorage.setItem('fort.agent-channel.last',agentID);localStorage.setItem('fort.agent-channel.'+agentID+'.conversation',id);renderAgents();setRail(false);const transcript=byID('transcript');transcript.innerHTML='<div class="loading-state">Loading durable conversation…</div>';try{state.detail=await request(conversationURL(agentID,id));renderConversation();startConversationEvents(agentID,id)}catch(error){transcript.innerHTML='';const wrap=node('div','error-state');const inner=node('div','empty-inner');inner.append(node('h2','', 'Conversation unavailable'));inner.append(node('p','',errorText(error)));wrap.append(inner);transcript.append(wrap);announce(errorText(error),'error')}}
function renderConversation(){const detail=state.detail||{};const agent=selectedAgent();const conversation=conversationOf(detail);agentHeader(agent,detail.readiness);byID('conversation-title').textContent=first(conversation.title,conversation.name,'Conversation');const binding=first(detail.binding,channelOf(agent).binding,{});const seat=first(binding.seat,{});const authority=first(binding.authority,{});byID('conversation-subtitle').textContent=[first(channelOf(agent).name,'Agent'),first(authority.resolved_model,authority.requested_model,seat.model,'model unknown'),first(seat.machine,'computer unknown'),first(detail.readiness&&detail.readiness.state,readiness(agent))].join(' · ');if(agentCanSend())byID('composer-context').textContent='Message '+first(channelOf(agent).name,'selected agent')+' in '+first(conversation.title,conversation.name,'this conversation');byID('pin-conversation').hidden=false;byID('pin-conversation').textContent=detail.pinned?'Unpin':'Pin';byID('rename-conversation').hidden=false;byID('archive-conversation').hidden=false;renderTranscript(detail);renderWorkingEnergy(detail)}
function renderTranscript(detail){const transcript=byID('transcript');clear(transcript);const messages=list(detail.messages);const targets=list(detail.targets);if(!messages.length&&!targets.length){const empty=node('div','empty-state');const inner=node('div','empty-inner');inner.append(node('h2','', 'Conversation ready'));inner.append(node('p','', 'Send a message to this exact agent.'));empty.append(inner);transcript.append(empty);return}messages.forEach(message=>{const human=String(first(message.author_kind,message.role,'')).toLowerCase()==='human';const article=node('article','message'+(human?' human':''));if(!human){article.append(node('span','agent-avatar message-avatar',initials(channelOf(selectedAgent()).name)))}const copy=node('div','message-copy');const byline=node('div','message-byline');byline.append(node('strong','',human?'You':first(channelOf(selectedAgent()).name,'Agent')));const time=node('time','',formatTime(first(message.created_at,message.recorded_at)));byline.append(time);copy.append(byline);copy.append(node('p','message-body',first(message.body,message.text,message.content,'')));if(!human){const authority=first(detail.binding&&detail.binding.authority,{});copy.append(node('p','message-attribution',[first(authority.resolved_model,authority.requested_model,'model unknown'),first(authority.adapter_id,'adapter unknown')].join(' · ')))}article.append(copy);transcript.append(article)});targets.filter(target=>String(first(target.state,target.status,'')).toLowerCase()!=='answered').forEach(target=>transcript.append(renderTarget(target)));transcript.scrollTop=transcript.scrollHeight}
function agentRecoveryActions(target){const code=String(first(target&&target.error_code,''));if(['seat_unready','primary_agent_unready','primary_agent_drift','chat_policy_unavailable'].includes(code))return['recheck_and_retry','retry'];if(['daemon_interrupted','provider_result_unknown','provider_incomplete','provider_failed'].includes(code))return['retry'];return[]}
function renderTarget(target){const status=String(first(target.state,target.status,'unknown')).toLowerCase();const card=node('article','target '+status);card.id='target-'+target.id;const head=node('div','target-head');const copy=node('div','target-copy');copy.append(node('strong','',status));copy.append(node('span','',first(target.error,target.reason,target.status_detail,'Durable target state')));head.append(copy);const actions=node('div','target-actions');if(status==='queued'||status==='working'){const cancel=node('button','quiet','Cancel');cancel.type='button';cancel.addEventListener('click',()=>cancelTarget(target.id,cancel));actions.append(cancel)}if(status==='failed'&&agentRecoveryActions(target).includes('retry')){const retry=node('button','secondary','Retry');retry.type='button';retry.addEventListener('click',()=>retryTarget(target.id,retry));actions.append(retry)}head.append(actions);card.append(head);return card}
function renderWorkingEnergy(detail){const working=list(detail&&detail.targets).some(target=>String(first(target.state,target.status,'')).toLowerCase()==='working');byID('fort-product-mark').dataset.energy='ambient';const scoped=byID('conversation-working');scoped.hidden=!working;byID('conversation-product-mark').dataset.energy=working?'working':'ambient';syncMarkLifecycle()}
function formatTime(value){if(!value)return'';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}
async function sendMessage(event){event.preventDefault();const input=byID('message-text');const text=input.value.trim();if(!text||!agentCanSend())return;const clientTurnID=pendingTurnIDFor(text);const button=byID('send-message');button.disabled=true;input.disabled=true;byID('composer-status').textContent='Committing durable turn…';try{if(state.creatingConversation||!state.selectedConversationID){const payload=await request(firstTurnURL(state.selectedAgentID),{method:'POST',body:JSON.stringify({name:conversationName(text),client_turn_id:clientTurnID,text})});clearPendingTurn(clientTurnID);const detail=first(payload&&payload.conversation,payload&&payload.detail,payload,{});const id=conversationID(detail);input.value='';if(id){await loadAgents(state.selectedAgentID,id)}else{await loadAgents(state.selectedAgentID)}announce('New conversation and first turn committed.')}else{await request(conversationURL(state.selectedAgentID,state.selectedConversationID)+'/turns',{method:'POST',body:JSON.stringify({client_turn_id:clientTurnID,text})});clearPendingTurn(clientTurnID);input.value='';await openConversation(state.selectedAgentID,state.selectedConversationID);announce('Turn committed to '+first(channelOf(selectedAgent()).name,'the selected agent')+'.')}}catch(error){announce(errorText(error),'error')}finally{const canSend=agentCanSend();input.disabled=!canSend;button.disabled=!canSend}}
function conversationName(text){const compact=text.replace(/\s+/g,' ').trim();return compact.length>54?compact.slice(0,51)+'…':compact||'New conversation'}
async function togglePin(){if(!state.detail)return;const button=byID('pin-conversation');button.disabled=true;try{await request(conversationURL(state.selectedAgentID,state.selectedConversationID),{method:'PATCH',body:JSON.stringify({pinned:!Boolean(state.detail.pinned)})});await loadAgents(state.selectedAgentID,state.selectedConversationID);announce(state.detail&&state.detail.pinned?'Conversation pinned.':'Conversation pin updated.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function retryTarget(id,button){button.disabled=true;try{await request(conversationURL(state.selectedAgentID,state.selectedConversationID)+'/targets/'+encode(id)+'/retry',{method:'POST'});await openConversation(state.selectedAgentID,state.selectedConversationID);announce('Retry kept the same agent identity.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function cancelTarget(id,button){button.disabled=true;try{await request(conversationURL(state.selectedAgentID,state.selectedConversationID)+'/targets/'+encode(id)+'/cancel',{method:'POST'});await openConversation(state.selectedAgentID,state.selectedConversationID);announce('Cancellation requested.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function loadOptions(recheck=false){const container=byID('agent-options');clear(container);container.append(node('p','', 'Loading server-resolved agent options…'));try{const payload=await request(API.options+(recheck?'/recheck':''),recheck?{method:'POST'}:{});const options=Array.isArray(payload)?payload:list(payload&&payload.options);clear(container);if(!options.length){container.append(node('p','', 'No Agent Channel options are currently available.'));return}options.forEach(option=>{const card=node('article','option-card');const head=node('div','option-card-head');head.append(node('strong','',first(option.display_name,'Agent option')));const add=node('button','secondary',option.state==='ready'?'Add':'Unavailable');add.type='button';add.disabled=option.state!=='ready';add.addEventListener('click',()=>promptAgentName(option,add));head.append(add);card.append(head);card.append(node('p','',first(option.reason,option.state)));card.append(factsFor(option.binding));container.append(card)})}catch(error){clear(container);container.append(node('p','rail-error',errorText(error)))}}
function promptAgentName(option,button){const name=prompt('Name this Agent Channel',first(option.display_name,'Agent'));if(!name)return;button.disabled=true;request(API.agents,{method:'POST',body:JSON.stringify({agent_option_id:option.agent_option_id,name:name.trim()})}).then(()=>{closeDialog(byID('agent-dialog'));return loadAgents()}).then(()=>announce('Agent Channel added.')).catch(error=>announce(errorText(error),'error')).finally(()=>{button.disabled=false})}
function factsFor(binding){const seat=first(binding&&binding.seat,{});const authority=first(binding&&binding.authority,{});const dl=node('dl','facts');[['Seat ID',seat.id],['Profile',seat.profile],['Agent / harness',seat.agent],['Seat model',seat.model],['Requested model',authority.requested_model],['Resolved model',first(authority.resolved_model,'unknown')],['Computer',seat.machine],['Authority',authority.authority],['Policy ID',authority.policy_id],['Policy revision',authority.policy_revision],['Adapter ID',authority.adapter_id],['Adapter revision',authority.adapter_revision],['Runtime contract',authority.runtime_contract],['Session',authority.session_mode],['Memory',authority.memory_mode]].forEach(pair=>{const wrap=node('div');wrap.append(node('dt','',pair[0]));wrap.append(node('dd','',first(pair[1],'unknown')));dl.append(wrap)});return dl}
function showIdentity(){const agent=selectedAgent();if(!agent)return;const channel=channelOf(agent);byID('identity-title').textContent=first(channel.name,'Agent identity');const content=byID('identity-content');clear(content);const card=node('article','identity-card');card.append(factsFor(channel.binding));card.append(node('p','', 'Readiness: '+String(readiness(agent))+' · '+readinessReason(agent)));const actions=node('div','dialog-actions');const rename=node('button','quiet','Rename agent');rename.type='button';rename.addEventListener('click',()=>renameSelectedAgent(rename));actions.append(rename);const archive=node('button','quiet','Archive agent');archive.type='button';archive.addEventListener('click',()=>archiveSelectedAgent(archive));actions.append(archive);const recheck=node('button','secondary','Recheck readiness');recheck.type='button';recheck.addEventListener('click',()=>recheckSelectedAgent(recheck));actions.append(recheck);card.append(actions);content.append(card);openDialog('identity-dialog')}
async function recheckSelectedAgent(button){const agentID=state.selectedAgentID;const conversationID=state.selectedConversationID;button.disabled=true;try{await request(API.options+'/recheck',{method:'POST'});closeDialog(byID('identity-dialog'));await loadAgents(agentID,conversationID);announce('Agent readiness rechecked without dispatching a turn.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function renameSelectedAgent(button){const agent=selectedAgent();if(!agent)return;const current=first(channelOf(agent).name,'Agent');const name=window.prompt('Rename this Agent Channel',current);if(!name||!name.trim()||name.trim()===current)return;button.disabled=true;try{await request(agentURL(state.selectedAgentID),{method:'PATCH',body:JSON.stringify({name:name.trim()})});closeDialog(byID('identity-dialog'));await loadAgents(state.selectedAgentID,state.selectedConversationID);announce('Agent Channel renamed. Immutable identity is unchanged.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function archiveSelectedAgent(button){if(!state.selectedAgentID)return;if(!window.confirm('Archive this Agent Channel? Its conversations stay durable.'))return;const agentID=state.selectedAgentID;button.disabled=true;try{await request(agentURL(agentID),{method:'PATCH',body:JSON.stringify({state:'archived'})});localStorage.removeItem('fort.agent-channel.last');closeDialog(byID('identity-dialog'));await loadAgents();announce('Agent Channel archived.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function showArchivedAgents(){closeDialog(byID('agent-dialog'));const container=byID('archived-agents-list');clear(container);container.append(node('p','', 'Loading archived Agent Channels…'));openDialog('archived-agents-dialog');try{const payload=await request(API.agents+'?state=archived');const items=Array.isArray(payload)?payload:list(payload&&payload.items);clear(container);if(!items.length){container.append(node('p','', 'No archived Agent Channels.'));return}items.forEach(item=>{const channel=channelOf(item);const card=node('article','archived-card');const head=node('div','archived-card-head');head.append(node('strong','',first(channel.name,'Agent')));const reopen=node('button','secondary','Reopen');reopen.type='button';reopen.addEventListener('click',()=>reopenAgent(channel.id,reopen));head.append(reopen);card.append(head);card.append(node('p','', first(channel.binding&&channel.binding.seat&&channel.binding.seat.agent,'Agent')+' · same immutable identity'));container.append(card)})}catch(error){clear(container);container.append(node('p','rail-error',errorText(error)))}}
async function reopenAgent(id,button){button.disabled=true;try{await request(agentURL(id),{method:'PATCH',body:JSON.stringify({state:'open'})});closeDialog(byID('archived-agents-dialog'));await loadAgents(id);announce('Agent Channel reopened with the same identity.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function loadNeeds(){try{const payload=await request(API.needs);state.needs=Array.isArray(payload)?payload:list(payload&&payload.items);byID('needs-count').hidden=!state.needs.length;byID('needs-count').textContent=String(state.needs.length)}catch(_){state.needs=[]}}
async function retryNeed(item,button){const agentID=String(first(item&&item.agent_channel&&item.agent_channel.id,''));const conversationID=String(first(item&&item.conversation&&item.conversation.id,''));const targetID=String(first(item&&item.target&&item.target.id,''));const recovery=list(item&&item.recovery_actions);if(!agentID||!conversationID||!targetID||!recovery.includes('retry'))return;button.disabled=true;try{if(recovery.includes('recheck_and_retry'))await request(API.options+'/recheck',{method:'POST'});await request(conversationURL(agentID,conversationID)+'/targets/'+encode(targetID)+'/retry',{method:'POST'});closeDialog(byID('needs-dialog'));await Promise.all([loadAgents(agentID,conversationID),loadNeeds()]);announce('Retry queued on the same agent identity.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
function showNeeds(){const container=byID('needs-list');clear(container);if(!state.needs.length)container.append(node('p','', 'Nothing currently needs you.'));state.needs.forEach(item=>{const agentID=String(first(item&&item.agent_channel&&item.agent_channel.id,''));const conversationID=String(first(item&&item.conversation&&item.conversation.id,''));const card=node('article','needs-card');card.append(node('strong','',first(item.agent_channel&&item.agent_channel.name,'Agent')+' · '+first(item.conversation&&item.conversation.title,'Conversation')));card.append(node('p','',first(item.target&&item.target.error,item.target&&item.target.state,'Action required')));const actions=node('div','target-actions');if(agentID&&conversationID){const open=node('button','quiet','Open conversation');open.type='button';open.addEventListener('click',()=>{closeDialog(byID('needs-dialog'));openConversation(agentID,conversationID)});actions.append(open)}const recovery=list(item.recovery_actions);if(agentID&&conversationID&&item.target&&item.target.id&&recovery.includes('retry')){const retry=node('button','secondary',recovery.includes('recheck_and_retry')?'Recheck and retry':'Retry');retry.type='button';retry.addEventListener('click',()=>retryNeed(item,retry));actions.append(retry)}card.append(actions);container.append(card)});openDialog('needs-dialog')}
function openNameDialog(){if(!state.detail)return;byID('name-title').textContent='Rename conversation';byID('name-input').value=first(conversationOf(state.detail).title,conversationOf(state.detail).name,'');openDialog('name-dialog')}
async function saveName(event){event.preventDefault();const name=byID('name-input').value.trim();if(!name)return;try{await request(conversationURL(state.selectedAgentID,state.selectedConversationID),{method:'PATCH',body:JSON.stringify({name})});closeDialog(byID('name-dialog'));await loadAgents(state.selectedAgentID,state.selectedConversationID);announce('Conversation renamed. Agent identity is unchanged.')}catch(error){announce(errorText(error),'error')}}
async function archiveConversation(){if(!state.detail||!state.selectedConversationID)return;if(!window.confirm('Archive this conversation? Its transcript stays durable and can be reopened.'))return;const agentID=state.selectedAgentID;const button=byID('archive-conversation');button.disabled=true;try{await request(conversationURL(agentID,state.selectedConversationID),{method:'PATCH',body:JSON.stringify({state:'archived'})});localStorage.removeItem('fort.agent-channel.'+agentID+'.conversation');await loadAgents(agentID);announce('Conversation archived.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
async function showArchivedConversations(){if(!state.selectedAgentID){announce('Choose an Agent Channel first.','error');return}const container=byID('archived-list');clear(container);container.append(node('p','', 'Loading archived conversations…'));openDialog('archived-dialog');try{const payload=await request(agentURL(state.selectedAgentID)+'/conversations?state=archived');const items=Array.isArray(payload)?payload:list(payload&&payload.items);clear(container);if(!items.length){container.append(node('p','', 'No archived conversations for this agent.'));return}items.forEach(item=>{const conversation=conversationOf(item);const card=node('article','archived-card');const head=node('div','archived-card-head');head.append(node('strong','',first(conversation.title,'Conversation')));const reopen=node('button','secondary','Reopen');reopen.type='button';reopen.addEventListener('click',()=>reopenConversation(conversation.id,reopen));head.append(reopen);card.append(head);card.append(node('p','', 'Reopens beneath the same immutable Agent Channel.'));container.append(card)})}catch(error){clear(container);container.append(node('p','rail-error',errorText(error)))}}
async function reopenConversation(id,button){button.disabled=true;try{await request(conversationURL(state.selectedAgentID,id),{method:'PATCH',body:JSON.stringify({state:'open'})});closeDialog(byID('archived-dialog'));await loadAgents(state.selectedAgentID,id);announce('Conversation reopened under the same agent.')}catch(error){announce(errorText(error),'error')}finally{button.disabled=false}}
const fortMarkObserver=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{entries.forEach(entry=>{entry.target.dataset.visible=String(entry.isIntersecting);syncMarkLifecycle()})}):null;
function syncMarkLifecycle(){const hidden=document.visibilityState!=='visible';document.querySelectorAll('.fort-mark').forEach(mark=>{if(fortMarkObserver&&!mark.dataset.observed){mark.dataset.observed='true';mark.dataset.visible='true';fortMarkObserver.observe(mark)}mark.dataset.motion=hidden||mark.dataset.visible==='false'?'paused':'running'})}
function bind(){byID('rail-open').addEventListener('click',()=>setRail(true));byID('rail-close').addEventListener('click',()=>setRail(false));byID('rail-backdrop').addEventListener('click',()=>setRail(false));byID('new-conversation').addEventListener('click',()=>{if(state.selectedAgentID)selectAgent(state.selectedAgentID);else announce('Choose an Agent Channel first.','error')});byID('add-agent').addEventListener('click',()=>{openDialog('agent-dialog');loadOptions()});byID('conversation-composer').addEventListener('submit',sendMessage);byID('pin-conversation').addEventListener('click',togglePin);byID('rename-conversation').addEventListener('click',openNameDialog);byID('archive-conversation').addEventListener('click',archiveConversation);byID('archived-conversations').addEventListener('click',showArchivedConversations);byID('name-form').addEventListener('submit',saveName);byID('inspect-agent').addEventListener('click',showIdentity);byID('settings').addEventListener('click',()=>{openDialog('agent-dialog');loadOptions()});byID('archived-agents').addEventListener('click',showArchivedAgents);byID('recheck-options').addEventListener('click',()=>loadOptions(true));byID('needs-you').addEventListener('click',showNeeds);document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>closeDialog(button.closest('dialog'))));document.addEventListener('visibilitychange',syncMarkLifecycle);window.addEventListener('beforeunload',stopConversationEvents);syncMarkLifecycle()}
async function start(){bind();try{await Promise.all([loadAgents(),loadNeeds()])}catch(error){announce(errorText(error),'error');const container=byID('agent-channel-list');clear(container);container.append(node('p','rail-error',errorText(error)))}}
start();
</script>
</body>
</html>`
